apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-operator.fullname" . }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tenant-operator.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "tenant-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --health-probe-bind-address={{ .Values.healthProbeBindAddress }}
        - --metrics-bind-address={{ .Values.metricsBindAddress }}
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: probes
        livenessProbe:
          httpGet:
            path: /healthz
            port: probes
        readinessProbe:
          httpGet:
            path: /readyz
            port: probes
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      serviceAccountName: {{ include "tenant-operator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
