apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant-operator.serviceAccountName" . }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
