apiVersion: tenant.cncamp.io/v1alpha1
kind: Tenant
metadata:
  name: demo
spec:
  namespace: demo
  adminUser: mfanjie
  objectCounts:
    configMaps: "20"
    secrets: "20"
    services: "10"
    loadBalancers: "20"
    nodePorts: "30"
