apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: web
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app: jenkins
---
# Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: jenkins-headless
  namespace: devops
  labels:
    app: jenkins
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: web
    - port: 50000
      name: agent
  selector:
    app: jenkins
