apiVersion: v2
name: tenant-operator
description: A Helm chart for tenant-operator - 多租户管理 Operator
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: cncamp
    email: cncamp@example.com
