apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-operator
  namespace: tenant-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-operator
  template:
    metadata:
      labels:
        app: tenant-operator
    spec:
      serviceAccountName: tenant-operator
      imagePullSecrets:
      - name: aliyun-cr
      containers:
      - name: manager
        image: crpi-j9gshcbjtb1i6c7h.cn-hangzhou.personal.cr.aliyuncs.com/tutengdihuang_docker_image/tenant-operator:latest
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: probes
        livenessProbe:
          httpGet:
            path: /healthz
            port: probes
        readinessProbe:
          httpGet:
            path: /readyz
            port: probes
